POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "asd",
    "important": true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "asdqwe",
    "important": true
}